apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deployment
  template:
    metadata:
      labels:
        app: mongo-deployment
        tier: backend
    spec:
      containers:
        - name: mongo-deployment
          image: mongo:latest
          env:
            - name: MONGO_DATA_DIR
              value: /data/db

          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume-mount
              mountPath: /data/db

      volumes:
        - name: mongo-volume-mount
          persistentVolumeClaim:
            claimName: mongo-pvc-ebs